services:
  postgres:
    image: postgres:15
    container_name: inventory-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventory-net

  app:
    image: ${DOCKER_IMAGE}
    container_name: inventory-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      HIBERNATE_DDL_AUTO: ${HIBERNATE_DDL_AUTO}
      APP_NAME: ${APP_NAME}
    networks:
      - inventory-net

volumes:
  postgres_data:

networks:
  inventory-net:

