#application.properties
spring.application.name=inventory_system

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/inventory_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:caddyshack1!!!}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

authorization.endpoint=${AUTHORIZATION_ENDPOINT:http://localhost:8081}
authorization.api.key=${SERVICE_API_KEY:dev-api-key}