name: Create docker-compose.yml

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  create-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate docker-compose.yml
        run: |
          cat > docker-compose.yml <<EOL
          services:
            app:
              build: .
              ports:
                - "8080:8080"
              environment:
                - SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE }}
                - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${{ secrets.DB_NAME }}
                - SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USER }}
                - SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}
              depends_on:
                - db

            db:
              image: postgres:latest
              environment:
                POSTGRES_DB: ${{ secrets.DB_NAME }}
                POSTGRES_USER: ${{ secrets.DB_USER }}
                POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
              ports:
                - "5432:5432"
          EOL

      - name: Upload docker-compose.yml as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose
          path: docker-compose.yml
